### ISSUE TITLE
Render problem 문제

### ISSUE THREAD

**Issue by Rose0001** [ssomai/ScalableLayout#45]
좋은 라이브러리 만들어 주셔서 감사합니다.

빌드를 하면 정상적으로 빌드되어 레이아웃이 적용 되나 미리보기가 제공되지 않아 불편함이 생겨 질의 드립니다.

빌드 버젼은 최소 21이며
타겟은 25입니다. 

xml 미리보기에서 Render errors 가 발생하여 아래와 같은 log가 발생하였습니다.

Render problem

java.lang.NoSuchFieldError: View_scale_left_baseposition   at com.ssomai.android.scalablelayout.ScalableLayout$LayoutParams.<init>(ScalableLayout.java:938)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:225)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:26)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:860)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 

아래는 xml 소스 코드 입니다.
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sl="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_login"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/login_imageview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop" />

    <com.ssomai.android.scalablelayout.ScalableLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        sl:scale_base_height="1600"
        sl:scale_base_width="1080"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true">

        <View
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/white"
            sl:scale_height="156"
            sl:scale_left="0"
            sl:scale_top="0"
            sl:scale_width="1080">

        </View>

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/arrow"
            sl:scale_height="52"
            sl:scale_left="45"
            sl:scale_top="78"
            sl:scale_top_baseposition="center"
            sl:scale_width="66" />

        <Button
            android:id="@+id/back_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/transparent"
            sl:scale_height="140"
            sl:scale_top="80"
            sl:scale_top_baseposition="center"
            sl:scale_width="170" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            sl:scale_left="540"
            sl:scale_top="80"
            sl:scale_top_baseposition="center"
            sl:scale_left_baseposition="center"
            sl:scale_width="300"
            sl:scale_height="100"
            sl:scale_textsize="45"
            android:gravity="center"
            android:textColor="@color/mainTextBlack"
            android:text="로그인" />

        <TextView
            android:id="@+id/check_textview"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/white"
            sl:scale_top="740"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_width="900"
            sl:scale_height="90"
            sl:scale_textsize="42"/>

        <View
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/white"
            sl:scale_height="160"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_top="355"
            sl:scale_width="990">

        </View>

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/d_email"
            sl:scale_height="38"
            sl:scale_left="80"
            sl:scale_top="435"
            sl:scale_top_baseposition="center"
            sl:scale_width="39" />

        <EditText
            android:id="@+id/id_edittext"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:gravity="center_vertical"
            android:hint="id@mail"
            android:maxLines="1"
            android:singleLine="true"
            sl:scale_height="160"
            sl:scale_left="160"
            sl:scale_textsize="45"
            sl:scale_top="355"
            sl:scale_width="850" />

        <View
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/white"
            sl:scale_height="160"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_top="550"
            sl:scale_width="990">

        </View>

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/d_pw"
            sl:scale_height="40"
            sl:scale_left="80"
            sl:scale_top="630"
            sl:scale_top_baseposition="center"
            sl:scale_width="39" />

        <EditText
            android:id="@+id/pw_edittext"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:gravity="center_vertical"
            android:hint="password"
            android:inputType="textPassword"
            android:maxLength="20"
            android:maxLines="1"
            sl:scale_height="160"
            sl:scale_left="160"
            sl:scale_textsize="45"
            sl:scale_top="550"
            sl:scale_width="850" />

        <Button
            android:id="@+id/login_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/border_login"
            android:text="LOGIN"
            android:textColor="@color/white"
            sl:scale_height="150"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_textsize="43"
            sl:scale_top="855"
            sl:scale_width="990" />

        <TextView
            android:id="@+id/signup_textview"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center|left"
            android:text="Join"
            android:textColor="@color/white"
            sl:scale_height="65"
            sl:scale_left="45"
            sl:scale_textsize="38"
            sl:scale_top="1020"
            sl:scale_width="100" />

        <TextView
            android:id="@+id/findpass_textview"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center|right"
            android:text="Find a password"
            android:textColor="@color/white"
            sl:scale_height="65"
            sl:scale_left="1030"
            sl:scale_left_baseposition="right"
            sl:scale_textsize="38"
            sl:scale_top="1020"
            sl:scale_width="300" />

        <Button
            android:id="@+id/facebook"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/border_login"
            android:gravity="center"
            android:text="Facebook Login"
            android:textColor="@color/white"
            sl:scale_height="150"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_textsize="43"
            sl:scale_top="1180"
            sl:scale_width="990" />

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/d_facebook"
            sl:scale_height="35"
            sl:scale_left="290"
            sl:scale_top="1255"
            sl:scale_top_baseposition="center"
            sl:scale_width="55" />

        <Button
            android:id="@+id/google"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/border_login"
            android:gravity="center"
            android:text="Google Login"
            android:textColor="@color/white"
            sl:scale_height="150"
            sl:scale_left="540"
            sl:scale_left_baseposition="center"
            sl:scale_textsize="43"
            sl:scale_top="1375"
            sl:scale_width="990" />

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/d_google"
            sl:scale_height="35"
            sl:scale_left="290"
            sl:scale_top="1450"
            sl:scale_top_baseposition="center"
            sl:scale_width="55" />

    </com.ssomai.android.scalablelayout.ScalableLayout>

</RelativeLayout>

**Comment by ssomai** [comment]
오! 자세한 리포팅 감사합니다
전 미리보기에서도 잘 나오긴하지만 ㅠㅠ
알려주신 코드 적용해서 확인해보겠습니다~
