### ISSUE TITLE
Render Problem

### ISSUE THREAD

**Issue by Blgrad** [ssomai/ScalableLayout#47]
안녕하세요. 잘 사용하고 있음에 먼저 감사드립니다.

 다름이아니라 복사한 프로젝트 내에서 Render Problem이 생겨서 문의드립니다.

 다른 원 컴퓨터에서는 정상적으로 레이아웃이 보입니다.

 1. Render Error나는 xml 레이아웃을 다른 scalablelayout 적용한 프로젝트에

   넣음 -> 정상작동

1. scalablelayout만 다른 레이아웃을 감싸서 아무것도 없이 적용시에는 미리보기가 되나
  안에 textview, button등 하나라도 들어가면 에러가 납니다.

 메시지는 아래와 같습니다. 감사합니다.

 java.lang.NoSuchFieldError: View_scale_left_baseposition   at com.ssomai.android.scalablelayout.ScalableLayout$LayoutParams.<init>(ScalableLayout.java:938)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:225)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:26)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:860)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

**Comment by ssomai** [comment]
안녕하세요~ 잘 사용하고 있으시다니 저도 감사드립니다.

혹시 gradle에서 scalablelayout 버전을 확인해봐주실수 있을까요~?

**Comment by Blgrad** [comment]
com.ssomai:android.scalablelayout:2.1.1 사용하고있습니다.

**Comment by ssomai** [comment]
Render problem이 발생하는 프로젝트도 같은 버전으로 사용중이신거죠~?

**Comment by Blgrad** [comment]
넵 같은 버전으로 사용하고있습니다.

**Comment by ssomai** [comment]
제가 재연이 어려운데, 혹시 관련 샘플 소스를 제가 받을수 있을까요~?

**Comment by Blgrad** [comment]
이게 발생하는 조건이 좀 애매합니다. 제가봤을땐 프로젝트 내 세팅의 문제(충돌?) 보입니다.
아마 소스를 받아도 발생하지 않을 가능성이 높은게 관련 부분만 따로 복사해서 옮기면 미리보기가 됩니다.

**Comment by ssomai** [comment]
아.... 음 재연이 어려워서 해결이 어렵네요~
저도 확인해보고 해결되면 업데이트할게요~
